# Generated by Django 4.2 on 2025-09-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_age_profile_city_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="Pet's age in years (if known)", null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', help_text="Pet's gender", max_length=10),
        ),
        migrations.AddField(
            model_name='petreport',
            name='name',
            field=models.CharField(blank=True, help_text="Pet's name (if known)", max_length=100, null=True),
        ),
    ]
