# Generated by Django 4.2 on 2025-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_petreport_age_petreport_gender_petreport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petreport',
            name='report_type',
            field=models.CharField(choices=[('Lost', 'Lost pet'), ('Found', 'Found pet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='petreport',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending Adoption', 'Pending Adoption'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
