# Generated by Django 4.2 on 2025-09-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_petreport_report_type_alter_petreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='health_information',
            field=models.TextField(blank=True, help_text='Any known health issues or required medication (Lost pet report).', null=True),
        ),
        migrations.AddField(
            model_name='petreport',
            name='injury',
            field=models.TextField(blank=True, help_text='Describe any injuries observed on the pet (Found pet report).', null=True),
        ),
    ]
