# Generated by Django 4.2 on 2025-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_petreport_health_information_petreport_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date the pet was lost or found.', null=True),
        ),
    ]
