# Generated by Django 4.2 on 2025-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_petreport_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
