# Generated by Django 4.2 on 2025-10-15 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_petreport_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petreport',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
